// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ausadhi_khau/models/medicine.dart';
import 'package:ausadhi_khau/models/medicine_schedule.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MedicineAdapter());
    registerAdapter(MedicineScheduleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MedicineAdapter());
    registerAdapter(MedicineScheduleAdapter());
  }
}
